### ISSUE TITLE
A question regarding EventID 4625

### ISSUE THREAD

**Issue by tbennett99** [EvotecIT/PSEventViewer#1]
First congratulations on an awesome module. Exactly what I need and so much more.

For event id 4625 - failed logon - is there a way to retrieve the Failure Reason as a string from the Message or from the Status and SubStatus fields?

                 Failure Information:
                        Failure Reason:         Unknown user name or bad password.
                        Status:                 0xC000006D
                        Sub Status:             0xC000006A

**Comment by PrzemyslawKlys** [comment]
```
$Test = Get-Events -ID 4625 -Machine AD1.ad.evotec.xyz6 -LogName 'Security' -MaxEvents 5
$Test[0] | Fl *
```

![image](https://user-images.githubusercontent.com/15063294/53938477-b4029280-40b0-11e9-9110-c4c059badfdb.png)

It would seem XML holds data but in a different format. Other fields are also there if you look closely.

**Comment by PrzemyslawKlys** [comment]
You could in theory go for spliting Message on \n and trying to read it. I was thinking on doing this in Get-Events for each event but haven't had time yet.

**Comment by PrzemyslawKlys** [comment]
Some more information on the ids https://social.technet.microsoft.com/Forums/en-US/9eac1798-36da-4b57-8c7e-e01072765bd4/failure-reasons-eg-2313-in-id-4625?forum=winserversecurity
