### ISSUE TITLE
Scriptblock.ps1 needs the updated version of Get-EventsFilter

### ISSUE THREAD

**Issue by danubie** [EvotecIT/PSEventViewer#10]
I recently discovered, that using Get-Events still does not return correct results, when using named filters - Even tough the Get-EventFilters bug has been fixed.
Now I recognized, that the function Get-Eventsfilter has to be maintained inside the scriptblock.ps1 as well.
PR will follow.
Remark: Currently I can not provide a test case for this, because named filter seem to not support reading from .evt files

**Comment by PrzemyslawKlys** [comment]
Thank you :-) Maybe there is a way to get Get-EventsFilter defined once and use it within Runspace. It doesn't make sense to keep 2 copies and causes the issue like yours.
