### ISSUE TITLE
Get-Events -Path does not work when using named filters

### ISSUE THREAD

**Issue by danubie** [EvotecIT/PSEventViewer#12]
I wanted to write a Pester test to validate issue #10. But reading from the example evtx file failes, because Get-Event (od Get-FilterEvents?) does not handle the -Path param in this use case.

I did not include the test in my latest PR, because the test (and the pipline) would fail due to this.
Here is a test to reproduce the problem:

    Describe 'Get-Events - Read events with NamedDataFilter' {
        $FilePath = [System.IO.Path]::Combine($PSScriptRoot, 'Logs', 'Active Directory Web Services.evtx')
        It 'Using named filter and -Path should not fail' {
            Get-Events -Path $FilePath -Oldest -MaxEvents 1 -ErrorVariable err
            $err | Should -BeNullOrEmpty
            Get-Events -Path $FilePath -NamedDataFilter @{ Data0 = ('blabla','blublu') } -Oldest -MaxEvents 1 -ErrorVariable err
            $err | Should -BeNullOrEmpty
        }
    }

**Comment by PrzemyslawKlys** [comment]
It fails for 3 reasons - Pester V5 change:

https://evotec.xyz/converting-pester-v4-to-pester-v5-basics/

```
Describe 'Get-Events - Read events with NamedDataFilter' {
    $FilePath = [System.IO.Path]::Combine($PSScriptRoot, 'Logs', 'Active Directory Web Services.evtx')
    $PSDefaultParameterValues = @{
        "It:TestCases" = @{ FilePath = $FilePath }
    }

    It 'Using named filter and -Path should not fail' {
        Get-Events -Path $FilePath -Oldest -MaxEvents 1 -ErrorVariable err
        $err | Should -BeNullOrEmpty
        Get-Events -Path $FilePath -NamedDataFilter @{ Data0 = ('blabla','blublu') } -Oldest -MaxEvents 1 -ErrorVariable err
        $err | Should -BeNullOrEmpty
    }
}
```
Second is:

```
    Get-WinEvent [-Path] <string[]> [-MaxEvents <long>] [-Credential <pscredential>] [-FilterXPath <string>] [-Oldest]  [<CommonParameters>]

    Get-WinEvent [-FilterHashtable] <hashtable[]> [-MaxEvents <long>] [-ComputerName <string>] [-Credential <pscredential>] [-Force] [-Oldest]  [<CommonParameters>]

    Get-WinEvent [-FilterXml] <xml> [-MaxEvents <long>] [-ComputerName <string>] [-Credential <pscredential>] [-Oldest]  [<CommonParameters>]
```

The Path is only available for FilterXPath and not FilterXML as far as I can see, and I am using FilterXML.

And 3rd one is lack of path for Get-EventsFilter in 2 places (one for outside use, one for during runspace use)

Btw. a tip for debugging this is to use -DisableParallel switch. It will cause breakpoints for easier testing.

Anyways, you can write a test that tests live events data. The pipelines execute this on "live" windows. Granted it will not have your usual dataset but basics yes, so if you query System or Application log with some basic queries assuming some things it should work. 

The big question is does FilterXML works on files and how the change looks like in XML code.

**Comment by danubie** [comment]
> The Path is only available for FilterXPath and not FilterXML as far as I can see, and I am using FilterXML

I know, that the "non named filter" approach uses the FilterXPath since last time when I was fixing the query syntax. That's the reason why I made the changes, tested Get-EventsFilter against my local eventlog "by hand" and made RP with just testing the inside function.
Yesterday I wanted prepare a script to use it - so I realized, that it does not work in the Get-Events.

>The big question is does FilterXML works on files and how the change looks like in XML code

I managed to get a working XML syntax for reading files as well. So now results from Get-EventsFilter should look good in both cases. I also will include an additional eventlog for named filter tests.

And finally: Thanks for the debugging hint. I already did this while hunting the bug today 🙂.

**Comment by PrzemyslawKlys** [comment]
I mentioned that because you would need to change it here:

https://github.com/EvotecIT/PSEventViewer/blob/2d512ccd3349b3bf1a6d01bde587cd3c83a2906e/Private/ScriptBlock.ps1#L629-L635

So that instead of Get-EvetnsFilter you would use it with proper switch ;-) That's it. Thanks for working on this. Really appreciate it.

**Comment by danubie** [comment]
It once again had to be fixed inside Get-EventsFilter. But after #13 it should work in both cases.

For the moment I'm fine with it and thanks for your little helper.
BTW: Next nice one would be to be able to query more than eventlog at a time (the query syntax would allow this).
Regards,
Wolfgang

**Comment by PrzemyslawKlys** [comment]
Thank you. Feel free to submit more commits if you ever get that working. I'm really glad you took time to add some tests. I struggle to write tests right away and then it's hard to get things running, causing breaking changes to go unnoticed.

**Comment by danubie** [comment]
> Thank you.

With pleasure.

> I struggle to write tests right away and then it's hard to get things running, causing breaking changes to go unnoticed.

I really appreciate to write test (but did not check Pester V5 changes and features).
Feel free to contact me. Maybe I can help one time or another.

**Comment by PrzemyslawKlys** [comment]
Well, not sure what's your interest but I do have 40 projects that could use some help. Starting from simple things like tests, to implementing things, to just verifying things do work as described (I just noticed PSWInDocumentation.O365 has some typos/bugs when returning data) or even writing docs :-) or even writing blog posts about them. There are many undocumented things (including features in PSEventViewer that you just added) that could help people achieve their goals. 

I'm more than happy to accept PRs anywhere. Be it simple things or more advanced ones.
