### ISSUE TITLE
Google chrome events not found when searching via ProviderName

### ISSUE THREAD

**Issue by ScrambledBrain** [EvotecIT/PSEventViewer#14]
Hi,

I have Google Chrome and MS Edge Chromium installed.
Both write events to application log, for example if they stop their update service:

```xml
Protokollname: Application
Quelle:        edgeupdate
Datum:         13.05.2021 10:57:55
Ereignis-ID:   0
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      PC1
Beschreibung:
Service stopped.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="edgeupdate" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-13T08:57:55.5989319Z" />
    <EventRecordID>10760</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>PC1</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Service stopped</Data>
  </EventData>
</Event>
```
```xml
Protokollname: Application
Quelle:        gupdate
Datum:         13.05.2021 11:14:39
Ereignis-ID:   0
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      PC1
Beschreibung:
Der Vorgang wurde erfolgreich beendet.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="gupdate" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-13T09:14:39.8749308Z" />
    <EventRecordID>10763</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>PC1</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Service stopped</Data>
  </EventData>
</Event>
```

But if I search events, only events of provider edgeupdate were found, not gupdate:

```powershell
[PS 5.1.19041] [ADMIN]: D:\Scripts> (Get-Events -LogName Application -ProviderName 'gupdate').count
0
[PS 5.1.19041] [ADMIN]: D:\Scripts> (Get-Events -LogName Application -ProviderName 'edgeupdate').count
456
```

It seems, something is bugged?

P.S.: great and interesting article about [Event Logs](https://evotec.xyz/powershell-everything-you-wanted-to-know-about-event-logs/) 👍🏻

**Comment by PrzemyslawKlys** [comment]
Get-Events uses Get-WinEvent beneath

![image](https://user-images.githubusercontent.com/15063294/118157228-9660ae80-b41a-11eb-847f-fb87c04133fc.png)

It would seem the provider is not registered or something. Which is weird:

![image](https://user-images.githubusercontent.com/15063294/118157707-31598880-b41b-11eb-8d92-ccae57e5a1a1.png)

![image](https://user-images.githubusercontent.com/15063294/118157773-42a29500-b41b-11eb-9db0-c8473e5e005b.png)

![image](https://user-images.githubusercontent.com/15063294/118158040-92815c00-b41b-11eb-9364-046bb08e735d.png)

So - it's more like a bug in Google Chrome not registering the provider properly.

**Comment by ScrambledBrain** [comment]
Holy crap, you are fast :D   
Thanks for answer =)
Google: Bad job done @.@
Microsoft: Better job done .. this time ^^

**Comment by ScrambledBrain** [comment]
Oh and little side note:
On https://evotec.xyz/hub/scripts/pseventviewer-powershell-module/
your link to issues points to https://github.com/EvotecIT/PSBlackListChecker/issues
instead to https://github.com/EvotecIT/PSEventViewer/issues
;D

**Comment by PrzemyslawKlys** [comment]
Thanks, fixed.
