### ISSUE TITLE
Digitaly Sign Module

### ISSUE THREAD

**Issue by PatrickOnGit** [EvotecIT/PSEventViewer#15]
Dear Przemyslaw

This module, unlike most others you made, are not digitally signed.
Could you consider to sign this module to allow running in environments with "AllSigned" execution policy?

Thank you very much.
Best regards
Patrick

**Comment by PrzemyslawKlys** [comment]
Sure, whenever I release a new version it's now signed by default. But this one has not had an upgrade for a while. I understand your requirement so I'll try to maybe fix something small and rerelease.
