### ISSUE TITLE
How can I install the module?

### ISSUE THREAD

**Issue by smallfish01** [EvotecIT/PSEventViewer#3]
Thanks for your provide the great module! I just downloaded "PSEventViewer" to my Windows 2012 server,  into the folder and running:
"Install-Module -Name PSEventViewer " 
Got the error:
+ Install-Module -Name PSEventViewer
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-Module:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Do you know how can I resolve the issue?

**Comment by PrzemyslawKlys** [comment]
This seems like a problem with PowerShell on your windows 2012 server. Make sure you update PS to 5.1 version https://www.microsoft.com/en-us/download/details.aspx?id=54616

After that update PowerShellGet... install-module powershellget -force

**Comment by smallfish01** [comment]
Thanks! it works after update PS!
