### ISSUE TITLE
-Path parameter

### ISSUE THREAD

**Issue by itpropaul** [EvotecIT/PSEventViewer#4]
It looks like based on at least one example (see below) that at one point in time there was a "-Path" parameter. This would be really nice to have for analyzing evtx files.

https://github.com/EvotecIT/PSEventViewer/blob/master/Examples/RunMe-Test%20File%20Scan%20Functionality.ps1

**Comment by PrzemyslawKlys** [comment]
For some weird reason, I've removed it. Seems like a bug, or just wasn't compatible with some other option. It's for sure something that should work. 

```powershell

    [CmdLetBinding()]
    param (
        [alias ("ADDomainControllers", "DomainController", "Server", "Servers", "Computer", "Computers", "ComputerName")] [string[]] $Machine = $Env:COMPUTERNAME,
        [alias ("StartTime", "From")][nullable[DateTime]] $DateFrom = $null,
        [alias ("EndTime", "To")][nullable[DateTime]] $DateTo = $null,
        [alias ("Ids", "EventID", "EventIds")] [int[]] $ID = $null,
        [alias ("ExludeEventID")][int[]] $ExcludeID = $null,
        [alias ("LogType", "Log")][string] $LogName = $null,
        [alias ("Provider")] [string] $ProviderName = '',
        [hashtable] $NamedDataFilter,
        [hashtable] $NamedDataExcludeFilter,
        [string[]] $UserID,
        [PSEventViewer.Level[]] $Level = $null,
        [string] $UserSID = $null,
        [string[]]$Data = $null,
        [int] $MaxEvents = $null,

        [ValidateNotNull()]
        [alias('Credentials')][System.Management.Automation.PSCredential]
        [System.Management.Automation.Credential()]$Credential = [System.Management.Automation.PSCredential]::Empty,

        #[string] $Path = $null,
        [PSEventViewer.Keywords[]] $Keywords = $null,
        [alias("EventRecordID")][int64] $RecordID,
        [int] $MaxRunspaces = [int]$env:NUMBER_OF_PROCESSORS + 1,
        [switch] $Oldest,
        [switch] $DisableParallel,
        [switch] $ExtendedOutput,
        [Array] $ExtendedInput
    )
```

It's actually commented out but the code is there. Care to uncomment it and see if it runs?

**Comment by itpropaul** [comment]
The line was completely missing form mine. I located where it should go, re-added it, and I get no results when trying to run it. Originally I just ran it against an evtx with no extra parameters but found that didn't work normally anyways. I then ran it like `Get-Events -Path "test.evtx" -id 1 -MaxEvents 10` and still no results.

**Comment by PrzemyslawKlys** [comment]
Not sure how you're testing it but works for me... Make sure to give full path to -Path. Probably a problem with finding the file. Use -Verbose if unsure.

**Comment by PrzemyslawKlys** [comment]
```powershell
Update-module pseventviewer
```

And usage:

```powershell

$FilePath = 'C:\Test\Archive-System-2019-11-18-16-45-35-050.evtx'

$Events = Get-Events -Path $FilePath -Oldest -MaxEvents 1 -Verbose
$Events

$EventsNewest = Get-Events -Path $FilePath -MaxEvents 1 -Verbose
$EventsNewest
```

Seems to work

**Comment by PrzemyslawKlys** [comment]
Closing as implemented.

**Comment by itpropaul** [comment]
Thanks @PrzemyslawKlys ! I just tested and it works great. I love that you have the oldest switch to go along with maxevents as well!
