### ISSUE TITLE
Support for PowerShell remoting (JEA) enpoint

### ISSUE THREAD

**Issue by adriandeller** [EvotecIT/PSEventViewer#5]
to overcome the "local admin" requirement and still read the event logs on remote computers (domain controllers), one could connect to a PowerShell remoting (JEA) enpoint.
could this be feasible by adding a new parameter(set) in function "Get-Events" ?

**Comment by PrzemyslawKlys** [comment]
I have to admit (shamefully) that I've never used JEA or set it up. I would be more than happy to have that support, just don't even know how to do it ;-)

**Comment by PrzemyslawKlys** [comment]
Closing as no idea what to do with it, and no details.
