### ISSUE TITLE
NamedDataFilter issue ?

### ISSUE THREAD

**Issue by nannnu** [EvotecIT/PSEventViewer#7]
hi PrzemySlaw.

I maybe wrong.. but hope you can guide in correct direction. I see that the following command always returns me incorrect results.

**Comment by nannnu** [comment]
Get-Events -LogName "forwardedevents" -id 4740,4771,4625 -NamedDataFilter @{'targetUserName'=('user3','user2','user1' )} -Verbose 

if user3 exists in the targetusername i get results only for 'user3' and if i put a nonexistent user in 'user3' , i do not get any output for 'user2' and 'user1' ... i tested out multiple times with only single users and multiple users and found that was the case. please let me know if i am doing something wrong.

Example : Transformed Xpath query from verbose output, when the user "SPAM" exists... the events i get are only for "SPAM" user and not for the other 2 users...

VERBOSE: Get-Events - Filter parameters provided LogName = forwardedevents
VERBOSE: Get-Events - Filter parameters provided NamedDataFilter with SubKey targetUserName = spam, vcuser, blah
VERBOSE: Get-Events - Events to process in Total (unique): 3
VERBOSE: Get-Events - Events to process in Total ID: 4625, 4740, 4771
VERBOSE: Get-Events - Running query with parallel enabled...
VERBOSE: Get-Events -------------START---------------------
VERBOSE: Get-Events - Inside<COMPUTERNAME> for Events ID: 4625 4740 4771
VERBOSE: Get-Events - Inside <COMPUTERNAME> for Events LogName: forwardedevents
VERBOSE: Get-Events - Inside <COMPUTERNAME> for Events RecordID:
VERBOSE: Get-Events - Inside<COMPUTERNAME>for Events Oldest: False
VERBOSE: Get-Events - Inside<COMPUTERNAME> - Custom FilterXML:
        <QueryList>
            <Query Id="0" Path="forwardedevents">
                <Select Path="forwardedevents">
                        (*[System[((EventID=4625) or (EventID=4740)) or (EventID=4771)]]) and
(*[EventData[Data[@Name='targetUserName'] = 'spam' or 'vcuser' or 'blah']])
                </Select>
            </Query>
        </QueryList>
VERBOSE: Get-Events - Inside <COMPUTERNAME> Events found 19
VERBOSE: Get-Events - Inside <COMPUTERNAME> Processing events...
VERBOSE: Get-Events - Inside <COMPUTERNAME>Time to generate 0 hours, 0 minutes, 17 seconds, 480 milliseconds
VERBOSE: Get-Events --------------END----------------------
VERBOSE: Get-Events - Overall errors: 0
VERBOSE: Get-Events - Overall events processed in total for the report: 19
VERBOSE: Get-Events - Overall time to generate 0 hours, 0 minutes, 17 seconds, 606 milliseconds
VERBOSE: Get-Events - Overall events processing end


EXAMPLE WHEN THE OUTPUT TOTALLY FAILS

VERBOSE: Get-Events - Filter parameters provided LogName = forwardedevents
VERBOSE: Get-Events - Filter parameters provided NamedDataFilter with SubKey targetUserName = spama, spam, blah
VERBOSE: Get-Events - Events to process in Total (unique): 3
VERBOSE: Get-Events - Events to process in Total ID: 4625, 4740, 4771
VERBOSE: Get-Events - Running query with parallel enabled...
VERBOSE: Get-Events -------------START---------------------
VERBOSE: Get-Events - Inside <COMPUTERNAME> for Events ID: 4625 4740 4771
VERBOSE: Get-Events - Inside <COMPUTERNAME> for Events LogName: forwardedevents
VERBOSE: Get-Events - Inside <COMPUTERNAME> for Events RecordID:
VERBOSE: Get-Events - Inside <COMPUTERNAME> for Events Oldest: False
VERBOSE: Get-Events - Inside <COMPUTERNAME> - Custom FilterXML:
        <QueryList>
            <Query Id="0" Path="forwardedevents">
                <Select Path="forwardedevents">
                        (*[System[((EventID=4625) or (EventID=4740)) or (EventID=4771)]]) and
(*[EventData[Data[@Name='targetUserName'] = 'spama' or 'spam' or 'blah']])
                </Select>
            </Query>
        </QueryList>
VERBOSE: Get-Events - Inside <COMPUTERNAME> No events found.
VERBOSE: Get-Events - Inside <COMPUTERNAME> Time to generate 0 hours, 0 minutes, 14 seconds, 892 milliseconds
VERBOSE: Get-Events --------------END----------------------
VERBOSE: Get-Events - Overall errors: 0
VERBOSE: Get-Events - Overall events processed in total for the report: 0
VERBOSE: Get-Events - Overall time to generate 0 hours, 0 minutes, 15 seconds, 25 milliseconds
VERBOSE: Get-Events - Overall events processing end

**Comment by PrzemyslawKlys** [comment]
Have you tried manually providing XPATH and dealing with targetUserName separately with Or?

```xml
<QueryList>
    <Query Id="0" Path="Security">
        <Select Path="Security"> (*[System[((EventID=4625) or (EventID=4740)) or (EventID=4771)]]) and ((*[EventData[Data[@Name='targetUserName'] = 'user1']]) or (*[EventData[Data[@Name='targetUserName'] = 'user2']]) or (*[EventData[Data[@Name='targetUserName'] = 'user3']]))
        </Select>
    </Query>
</QueryList>
```

You can try something like that in Event Viewer, see if it works and then we could try and fix autogeneration. Unless it specifically works for other types just not in this case but as you can see with how to separate event IDs are handled I would say it needs fixing.

**Comment by nannnu** [comment]
by the way the module is amazingly helpful...i have been meaning to use is from before, but got to it just now :)

Yep... separately with OR like you mentioned or even separately like below , works fine  (below is how i use it... but was looking at the other formatting you offered)



<QueryList>
  <Query Id="0" Path="forwardedevents">
    <Select Path="forwardedevents">
*[System[(EventID=4771 or EventID=4625 or EventID=4740)]] 
and *[EventData[Data[@Name='TargetUserName'] and
 (Data = 'bhbhbh'  or Data = 'okokol' or Data = 'asdskjhfj' or Data = 's0g01sj') 
  ]]
and *[System[TimeCreated[timediff(@SystemTime) &lt;= 2300000]]]
</Select>
  </Query>
</QueryList>

**Comment by PrzemyslawKlys** [comment]
I am a bit confused now? So what works and what doesn't work? What works in `PSEventViewer`,`Get-winEvent` or `Event Viewer`?  

It's cool that you like the module. It saves time and solves a lot of issues especially for querying multiple servers.

**Comment by nannnu** [comment]
the Get-events with the following FilterXML does not work as well as it does not work from EVENT VIEWER specifying the query

VERBOSE: Get-Events - Inside <COMPUTERNAME> - Custom FilterXML:
        <QueryList>
            <Query Id="0" Path="forwardedevents">
                <Select Path="forwardedevents">
                        (*[System[((EventID=4625) or (EventID=4740)) or (EventID=4771)]]) and
(*[EventData[Data[@Name='targetUserName'] = 'spama' or 'spam' or 'blah']])
                </Select>
            </Query>
        </QueryList>


separating with -OR statements work

**Comment by nannnu** [comment]
this does not work from Get-events or event viewer

        <QueryList>
            <Query Id="0" Path="forwardedevents">
                <Select Path="forwardedevents">
                        (*[System[((EventID=4625) or (EventID=4740)) or (EventID=4771)]]) and
(*[EventData[Data[@Name='targetUserName'] = 'spama' or 'spam' or 'blah']])
                </Select>
            </Query>
        </QueryList>

**Comment by nannnu** [comment]
the following did not work as well

<QueryList>
  <Query Id="0" Path="Security">
    <Select Path="Security"> (*[System[((EventID=4625) or (EventID=4740)) or (EventID=4771)]]) and ((*[EventData[Data[@Name='targetUserName'] = 'spam']]) or (*[EventData[Data[@Name='targetUserName'] = 'spama']]) or (*[EventData[Data[@Name='targetUserName'] = 'user3']]))
        </Select>
  </Query>
</QueryList>

**Comment by nannnu** [comment]
the following is my method and it works

  <Query Id="0" Path="forwardedevents">
    <Select Path="forwardedevents">
*[System[(EventID=4771 or EventID=4625 or EventID=4740)]] 
and *[EventData[Data[@Name='TargetUserName'] and
 (Data = 'mammmm'  or Data = 'aaaal' or Data = 'bbbb' ) 
  ]]
and *[System[TimeCreated[timediff(@SystemTime) &lt;= 2300000]]]
</Select>
  </Query>
</QueryList>

**Comment by PrzemyslawKlys** [comment]
Yes, but it isn't what you want when it comes to TargetUserName or is it?

**Comment by nannnu** [comment]
yep the method i posted above which works for me, i have put non-existent user names, jsut didnt want to share what i have in my AD...

**Comment by nannnu** [comment]
if i am still confusing you, ill try to hit you up on FB / Powershell group / Messenger ? Let me know

**Comment by PrzemyslawKlys** [comment]
You are :-) I am trying to figure out how to fix or help with this. I understand you don't want to show your data but your examples from the top don't match the last example where you ask for a single TargetUserName and require Data to be mamm or Data = all and so on. Either you're replacing way too much in your query or I completely lost you :-)

**Comment by PrzemyslawKlys** [comment]
You can continue here or discord (http://poshcode.org/discord which is great PS resource) or twitter. Facebook I treat a bit personally.

**Comment by nannnu** [comment]
sounds good..
WORKS

<QueryList>
  <Query Id="0" Path="forwardedevents">
    <Select Path="forwardedevents">
*[System[(EventID=4771 or EventID=4625 or EventID=4740)]] 
and *[EventData[Data[@Name='TargetUserName'] and
 (Data = 'spam'  or Data = 'vcuser' or Data = 'masteraccount' )
  ]]
</Select>
  </Query>
</QueryList>


DOES NOT WORK

<QueryList>
  <Query Id="0" Path="forwardedevents">
    <Select Path="forwardedevents">
(*[System[((EventID=4625) or (EventID=4740)) or (EventID=4771)]]) and ((*[EventData[Data[@name='targetUserName'] = 'spam']]) or (*[EventData[Data[@name='targetUserName'] = 'vcuser']]) or (*[EventData[Data[@name='targetUserName'] = 'masteraccount']]))
</Select>
  </Query>
</QueryList>

DOES NOT WORK

<QueryList>
  <Query Id="0" Path="forwardedevents">
    <Select Path="forwardedevents">
                        (*[System[((EventID=4625) or (EventID=4740)) or (EventID=4771)]]) and
(*[EventData[Data[@Name='targetUserName'] = 'spam' or 'vcuser' or 'masteraccount']])
                </Select>
  </Query>
</QueryList>

The last one is got by using Get-events and giving @nameddatafield 
Get-Events -LogName "forwardedevents" -id 4740,4771,4625 -NamedDataFilter @{'targetUserName'=('
spam','vcuser' ,'masteraccount')} -Verbose | select -ExpandProperty message


Let me know if this makes sense ?

**Comment by PrzemyslawKlys** [comment]
A bit more yes :-) A bit weird that it would work for the first way

**Comment by PrzemyslawKlys** [comment]
Please test new version when it gets released.
